/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRendererInterface extends ethers.utils.Interface {
  functions: {
    "tokenURI(uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;

  events: {};
}

export class IRenderer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRendererInterface;

  functions: {
    tokenURI(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "tokenURI(uint256,bytes32)"(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  tokenURI(
    tokenId: BigNumberish,
    node: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "tokenURI(uint256,bytes32)"(
    tokenId: BigNumberish,
    node: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    tokenURI(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "tokenURI(uint256,bytes32)"(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    tokenURI(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenURI(uint256,bytes32)"(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    tokenURI(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenURI(uint256,bytes32)"(
      tokenId: BigNumberish,
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
