/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISoulRegistrarInterface extends ethers.utils.Interface {
  functions: {
    "changePermissionContract(address)": FunctionFragment;
    "register(string,bytes32,string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changePermissionContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, BytesLike, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "changePermissionContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {};
}

export class ISoulRegistrar extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISoulRegistrarInterface;

  functions: {
    changePermissionContract(
      _newPermissionContract: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changePermissionContract(address)"(
      _newPermissionContract: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    register(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "register(string,bytes32,string,address)"(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  changePermissionContract(
    _newPermissionContract: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changePermissionContract(address)"(
    _newPermissionContract: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  register(
    rootName_: string,
    rootNode_: BytesLike,
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "register(string,bytes32,string,address)"(
    rootName_: string,
    rootNode_: BytesLike,
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    changePermissionContract(
      _newPermissionContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changePermissionContract(address)"(
      _newPermissionContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    register(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "register(string,bytes32,string,address)"(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changePermissionContract(
      _newPermissionContract: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changePermissionContract(address)"(
      _newPermissionContract: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    register(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "register(string,bytes32,string,address)"(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changePermissionContract(
      _newPermissionContract: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changePermissionContract(address)"(
      _newPermissionContract: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    register(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "register(string,bytes32,string,address)"(
      rootName_: string,
      rootNode_: BytesLike,
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
