/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IOwnableEvents } from "../IOwnableEvents";

export class IOwnableEvents__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOwnableEvents {
    return new Contract(address, _abi, signerOrProvider) as IOwnableEvents;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
];
